name: untitled
description: "Une application Flutter éducative interactive pour les élèves du primaire."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.0
  provider: ^6.1.1
  flutter_svg: ^2.0.7
  path_provider: ^2.0.15
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sokrat.jpg
    - assets/avatar.jpg
    - assets/avar.jpg

#  fonts:
#    - family: ComicNeue
#      fonts:
#        - asset: assets/fonts/ComicNeue-Regular.ttf
#        - asset: assets/fonts/ComicNeue-Bold.ttf
#          weight: 700

